"""empty message

Revision ID: 399e48fe5824
Revises: c9511551c7e0
Create Date: 2019-05-25 22:44:20.858702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399e48fe5824'
down_revision = 'c9511551c7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_items', sa.Column('sold', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_items', 'sold')
    # ### end Alembic commands ###
