"""empty message

Revision ID: 509042e9dccb
Revises: 399e48fe5824
Create Date: 2019-05-25 23:07:49.740402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509042e9dccb'
down_revision = '399e48fe5824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_items', sa.Column('left', sa.Integer(), nullable=False))
    op.drop_column('shop_items', 'sold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_items', sa.Column('sold', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('shop_items', 'left')
    # ### end Alembic commands ###
