"""empty message

Revision ID: c9511551c7e0
Revises: e17ec37a9a7a
Create Date: 2019-05-25 21:20:00.408722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9511551c7e0'
down_revision = 'e17ec37a9a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('shop', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_items')
    # ### end Alembic commands ###
