"""empty message

Revision ID: 02702467cfed
Revises: 1204b7f96bbe
Create Date: 2019-05-01 00:33:06.713734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02702467cfed'
down_revision = '1204b7f96bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_deposists',
    sa.Column('deposit_number', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_number'], ['tickets.ticket_number'], ),
    sa.PrimaryKeyConstraint('deposit_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_deposists')
    # ### end Alembic commands ###
