"""empty message

Revision ID: 1a94051cf334
Revises: 
Create Date: 2019-05-13 15:37:27.502153

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1a94051cf334'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
                    sa.Column('ticket_number', sa.String(length=8), nullable=False),
                    sa.Column('firstname', sa.String(length=30), nullable=False),
                    sa.Column('lastname', sa.String(length=30), nullable=False),
                    sa.Column('email', sa.String(length=30), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Boolean(), nullable=False),
                    sa.Column('price', sa.Float(precision=2), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('ticket_number')
                    )
    op.create_table('account_deposists',
                    sa.Column('deposit_number', sa.Integer(), nullable=False),
                    sa.Column('ticket_number', sa.String(length=8), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['ticket_number'], ['tickets.ticket_number'], ),
                    sa.PrimaryKeyConstraint('deposit_number')
                    )
    op.create_table('payment_accounts',
                    sa.Column('ticket_number', sa.String(length=8), nullable=False),
                    sa.Column('balance', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['ticket_number'], ['tickets.ticket_number'], ),
                    sa.PrimaryKeyConstraint('ticket_number')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_accounts')
    op.drop_table('account_deposists')
    op.drop_table('tickets')
    # ### end Alembic commands ###
