"""empty message

Revision ID: 1e1c8aea243a
Revises: 
Create Date: 2019-05-12 00:15:14.468396

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1e1c8aea243a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
                    sa.Column('review_id', sa.Integer(), nullable=False),
                    sa.Column('publisher', sa.String(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('review_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
