"""empty message

Revision ID: 80ec655209ec
Revises: c96525ce217c
Create Date: 2019-04-18 20:17:19.137703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80ec655209ec'
down_revision = 'c96525ce217c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountDeposit',
    sa.Column('deposit_number', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('deposit_number')
    )
    op.drop_table('AccountDeposti')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountDeposti',
    sa.Column('deposit_number', sa.INTEGER(), server_default=sa.text('nextval(\'"AccountDeposti_deposit_number_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('deposit_number', name='AccountDeposti_pkey')
    )
    op.drop_table('AccountDeposit')
    # ### end Alembic commands ###
