"""empty message

Revision ID: 9df0c550eefb
Revises: 80ec655209ec
Create Date: 2019-04-18 20:27:30.113691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df0c550eefb'
down_revision = '80ec655209ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'AccountDeposit', 'Ticket', ['ticket_number'], ['ticket_number'])
    op.create_foreign_key(None, 'Client', 'Ticket', ['ticket_number'], ['ticket_number'])
    op.create_foreign_key(None, 'PaymentAccount', 'Ticket', ['ticket_number'], ['ticket_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PaymentAccount', type_='foreignkey')
    op.drop_constraint(None, 'Client', type_='foreignkey')
    op.drop_constraint(None, 'AccountDeposit', type_='foreignkey')
    # ### end Alembic commands ###
