"""empty message

Revision ID: 1a9d379f98b2
Revises: 6f4c4ce404ab
Create Date: 2019-06-01 19:28:27.355502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9d379f98b2'
down_revision = '6f4c4ce404ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spending_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shop_items', sa.Column('initial_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_items', 'initial_quantity')
    op.drop_table('spending_history')
    # ### end Alembic commands ###
